version: '3.3'

services:

  db:
    image: mysql
    container_name: mysql_db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql-data:/var/lib/mysql

  wordpress:
    image: wordpress:latest
    container_name: wordpress
    restart: always
    ports:
      - 80:80
    environment:
      WORDPRESS_DB_PASSWORD: root
      WORDPRESS_DB_HOST: db
    volumes:
      - ./plugins/country-and-currency:/var/www/html/wp-content/plugins/country-and-currency
      - ./themes/company:/var/www/html/wp-content/themes/company

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  mysql-data:
    driver: local
